# Fabrication run config for abb_rcf_runner
# YAML format, https://yaml.org/spec/1.2
# All values are required unless marked optional
robot_movement:
    speed_override: 100 # %
    speed_max_tcp: 500 # mm/s
    accel: 100 # mm/s^2
    accel_ramp: 100 # %, optional, default 100, the rate at which acceleration
                    # increases or decreases as a percentage of the normal values
    offset_distance: 200 # mm, last frame before placing picking is offset by
                         # this distance
    # velocities defined as mm/s
    speed_placing: 150 # mm/s
    speed_picking: 150 # mm/s
    speed_travel: 250 # mm/s
    # Either rapid variable name or mm
    zone_pick: 'Fine' # case doesn't matter here
    zone_place: 'FINE'
    zone_travel: 'Z150'
    compress_at_pick: 0.05 # controls compression before lifting
    needles_pause: 0.5 # Seconds to wait before and after extending or
                       # retracting needles
robot_joint_pos: # used at start and end of fabrication run
    # 6 joint values in degrees
    end: [ -127.0, 54.0, 9.0 , 2.0 , 30.0, 7.0 ] # 6 joint values in degrees
    start: [ -127.0, 54.0, 9.0, -2.0, 30.0, 7.0 ] # 6 joint values in degrees
tools:
    pick_place:
        tool_name: t_A057_ClayTool01 # name of tool
        io_needles_pin: doDNetOut1 # name of DO
        extend_signal: 1 # state (0 or 1)
        retract_signal: 0 # state (0 or 1)
        tool0_z_dist: 400
    dist_sensor:
        tool_name: t_A057_DistSensor01 # name of tool
        serial_port: COM1
        serial_baudrate: 115200
        tool0_z_dist: 300
wobjs:
    # name of work objects as defined in controller
    picking_wobj_name: wobj0
    placing_wobj_name: ob_A057_WobjPlacing01
docker:
    timeout_ping: 10
    sleep_after_up: 5
paths:
    log_dir: G:\Shared drives\2020_MAS\T3\RCF-T3-Thesis\09-robot-control\03_fabrication_logs
