version: '3.5'
# run using this command:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  abb-planner:
    environment:
      - DISPLAY=host.docker.internal:0.0
    command:
      - roslaunch
      - --wait
      - moveit_setup_assistant
      - setup_assistant.launch
    volumes:
        - ./volume:/volume
